const canvas=document.querySelector('#universe'),ctx=canvas.getContext('2d',{alpha:false,desynchronized:true}),$=s=>document.querySelector(s);
const rand=(a,b)=>a+Math.random()*(b-a),clamp=(n,a,b)=>Math.max(a,Math.min(b,n)),lerp=(a,b,t)=>a+(b-a)*t;
const mobile=matchMedia('(pointer:coarse)').matches||innerWidth<760,cores=navigator.hardwareConcurrency||4;
let quality=mobile?.56:cores<=4?.68:1,W=0,H=0,DPR=1,last=0,time=0,moving=true,dragging=false,audio=null,journey=false,journeyTime=0,flash=0,frames=0,fpsClock=performance.now(),degraded=false;
const pointer={x:0,y:0,tx:0,ty:0};let stars=[],galaxy=[],floaters=[],bursts=[],ripples=[],petals=[],sprites=[],bgCanvas,trailClock=0;

function makeFlowerSprite(size){const c=document.createElement('canvas'),d=Math.ceil(size*2.8);c.width=c.height=d;const g=c.getContext('2d'),r=size,x=d/2,y=d/2;g.translate(x,y);g.shadowColor='rgba(255,183,15,.6)';g.shadowBlur=r*.45;for(let i=0;i<8;i++){g.save();g.rotate(i*Math.PI/4);const p=g.createLinearGradient(0,-r*.15,0,-r);p.addColorStop(0,'#e89505');p.addColorStop(.55,'#ffd83e');p.addColorStop(1,'#fff1a0');g.fillStyle=p;g.beginPath();g.moveTo(0,-r*.06);g.bezierCurveTo(-r*.4,-r*.3,-r*.36,-r*.83,0,-r);g.bezierCurveTo(r*.36,-r*.83,r*.4,-r*.3,0,-r*.06);g.fill();g.restore()}g.shadowBlur=0;const center=g.createRadialGradient(-r*.1,-r*.12,0,0,0,r*.42);center.addColorStop(0,'#ffce3c');center.addColorStop(.48,'#995300');center.addColorStop(1,'#321800');g.fillStyle=center;g.beginPath();g.arc(0,0,r*.38,0,7);g.fill();return c}
function buildSprites(){sprites=[makeFlowerSprite(16),makeFlowerSprite(32),makeFlowerSprite(64)]}
function buildBackground(){bgCanvas=document.createElement('canvas');bgCanvas.width=Math.max(1,Math.round(W*.5));bgCanvas.height=Math.max(1,Math.round(H*.5));const g=bgCanvas.getContext('2d'),w=bgCanvas.width,h=bgCanvas.height,b=g.createRadialGradient(w*.68,h*.47,0,w*.55,h*.5,Math.max(w,h));b.addColorStop(0,'#181202');b.addColorStop(.24,'#0d0a02');b.addColorStop(.58,'#06060a');b.addColorStop(1,'#010105');g.fillStyle=b;g.fillRect(0,0,w,h)}
function resize(){DPR=Math.min(devicePixelRatio||1,mobile?1.15:1.5);W=innerWidth;H=innerHeight;canvas.width=Math.round(W*DPR);canvas.height=Math.round(H*DPR);canvas.style.width=W+'px';canvas.style.height=H+'px';ctx.setTransform(DPR,0,0,DPR,0,0);buildBackground();seed()}
function seed(){const starCount=Math.round((mobile?320:620)*quality),galaxyCount=Math.round((mobile?145:300)*quality),floaterCount=Math.round((mobile?16:34)*quality),petalCount=Math.round((mobile?38:70)*quality);stars=Array.from({length:starCount},()=>({x:rand(0,W),y:rand(0,H),z:rand(.1,1),s:rand(.3,1.35),p:rand(0,7)}));galaxy=[];const arms=mobile?3:5;for(let i=0;i<galaxyCount;i++){const q=i/galaxyCount,arm=i%arms,a=q*11+arm*Math.PI*2/arms+rand(-.22,.22);galaxy.push({a,r:q*Math.min(W,H)*.57,z:rand(.25,1),s:rand(1.8,5.8),spin:rand(0,7),flower:Math.random()<.78})}floaters=Array.from({length:floaterCount},()=>({x:rand(-.05,1.05)*W,y:rand(-.1,1.1)*H,z:rand(.2,1),s:rand(7,21),phase:rand(0,7),vy:rand(.04,.16)}));petals=Array.from({length:petalCount},()=>makePetal(rand(0,W),rand(-H,H)))}
function makePetal(x,y){return{x,y,vx:rand(-.16,.16),vy:rand(.14,.55),s:rand(2,6),r:rand(0,7),vr:rand(-.035,.035),a:rand(.2,.75)}}
function stampFlower(x,y,r,rot=0,alpha=1){if(r<.5||x<-r*2||x>W+r*2||y<-r*2||y>H+r*2)return;const sprite=sprites[r>24?2:r>11?1:0],d=r*2.8;ctx.globalAlpha=alpha;if(r<7){ctx.drawImage(sprite,x-d/2,y-d/2,d,d)}else{ctx.save();ctx.translate(x,y);ctx.rotate(rot);ctx.drawImage(sprite,-d/2,-d/2,d,d);ctx.restore()}ctx.globalAlpha=1}
function drawPetal(x,y,s,r,a){ctx.save();ctx.translate(x,y);ctx.rotate(r);ctx.globalAlpha=a;ctx.fillStyle='#ffd344';ctx.beginPath();ctx.ellipse(0,-s,s*.55,s,0,0,7);ctx.fill();ctx.restore();ctx.globalAlpha=1}
function background(){ctx.drawImage(bgCanvas,0,0,W,H);const g=ctx.createRadialGradient(W*.68+pointer.x*12,H*.48+pointer.y*8,0,W*.68,H*.48,Math.min(W,H)*.48);g.addColorStop(0,'rgba(255,190,22,.13)');g.addColorStop(.3,'rgba(160,91,0,.045)');g.addColorStop(1,'transparent');ctx.fillStyle=g;ctx.fillRect(0,0,W,H)}
function drawStars(now){ctx.fillStyle='#ffe681';for(const s of stars){ctx.globalAlpha=.15+.5*(.5+.5*Math.sin(now*.0012+s.p));ctx.beginPath();ctx.arc(s.x+pointer.x*13*s.z,s.y+pointer.y*8*s.z,s.s*s.z,0,7);ctx.fill()}ctx.globalAlpha=1}
function drawGalaxy(now){const cx=W*(mobile?.67:.72)+pointer.x*18,cy=H*.48+pointer.y*11,base=now*.00003,maxR=Math.min(W,H)*.62;for(const f of galaxy){const a=f.a+base*(.4+f.z),x=cx+Math.cos(a)*f.r+Math.cos(a*2.3)*f.r*.08,y=cy+Math.sin(a)*f.r*.31,fade=clamp(1-f.r/maxR,.08,.78),size=f.s*(.42+f.z*.58)*(1+fade*.45);f.flower?stampFlower(x,y,size,f.spin+now*.00022,fade):drawPetal(x,y,size*.5,a,fade*.75)}for(let i=0;i<11;i++){const a=i*2.399+base*4,r=Math.sqrt(i)*8;stampFlower(cx+Math.cos(a)*r,cy+Math.sin(a)*r*.42,16*(1-i/22),a,.82)}}
function drawFloaters(now){for(const f of floaters){f.y+=f.vy*(.4+f.z);if(f.y>H+45){f.y=-45;f.x=rand(0,W)}stampFlower(f.x+pointer.x*28*f.z+Math.sin(now*.0006+f.phase)*6*f.z,f.y+pointer.y*13*f.z,f.s*(.45+f.z),Math.sin(now*.0003+f.phase)*.2,.2+f.z*.62)}}
function drawAmbientPetals(){for(const p of petals){p.x+=p.vx+Math.sin(time*.001+p.r)*.1;p.y+=p.vy;p.r+=p.vr;if(p.y>H+20)Object.assign(p,makePetal(rand(0,W),rand(-H*.3,-15)));drawPetal(p.x+pointer.x*9,p.y,p.s,p.r,p.a)}}
function explode(x,y,power=1){ripples.push({x,y,r:3,a:1});const amount=Math.round((mobile?18:28)*power*quality),cap=mobile?180:360;for(let i=0;i<amount;i++){const a=rand(0,7),speed=rand(1.1,6.3)*power;bursts.push({x,y,vx:Math.cos(a)*speed,vy:Math.sin(a)*speed-rand(0,1.5),life:1,decay:rand(.009,.018)/Math.sqrt(power),s:rand(3.5,9)*Math.sqrt(power),r:rand(0,7),vr:rand(-.07,.07),flower:Math.random()<.5,gravity:rand(.014,.04)})}if(bursts.length>cap)bursts.splice(0,bursts.length-cap);flash=Math.min(1,flash+.25*power);chime(power>1.2)}
function drawBursts(){for(let i=bursts.length-1;i>=0;i--){const b=bursts[i];b.x+=b.vx;b.y+=b.vy;b.vx*=.991;b.vy+=b.gravity;b.r+=b.vr;b.life-=b.decay;const size=b.s*(.35+b.life);b.flower?stampFlower(b.x,b.y,size,b.r,b.life):drawPetal(b.x,b.y,size*.6,b.r,b.life);if(b.life<=0)bursts.splice(i,1)}for(let i=ripples.length-1;i>=0;i--){const r=ripples[i];r.r+=4.5;r.a-=.032;ctx.strokeStyle=`rgba(255,211,69,${r.a*.45})`;ctx.lineWidth=1;ctx.beginPath();ctx.arc(r.x,r.y,r.r,0,7);ctx.stroke();if(r.a<=0)ripples.splice(i,1)}}
function startJourney(){if(journey)return;journey=true;journeyTime=0;document.body.classList.add('traveling');$('#chapter').classList.add('show');chime(true)}
function updateJourney(dt){if(!journey)return;journeyTime+=dt;const p=clamp(journeyTime/7200,0,1),stage=Math.min(2,Math.floor(p*3)),titles=['EL PRIMER BROTE','LLUVIA DE GIRASOLES','EXPLOSIÓN DORADA'];$('#progress').style.width=p*100+'%';$('#chapterNumber').textContent='0'+(stage+1);$('#chapterTitle').textContent=titles[stage];if(Math.random()<(mobile?.045:.075)+stage*.025){const a=rand(0,7),r=rand(30,Math.min(W,H)*.38),cx=W*(mobile?.55:.69),cy=H*.48;explode(cx+Math.cos(a)*r,cy+Math.sin(a)*r*.55,.5+stage*.18)}if(p>=1){journey=false;document.body.classList.remove('traveling');document.body.classList.add('modal');$('#message').classList.add('show');$('#message').setAttribute('aria-hidden','false');explode(W/2,H/2,mobile?1.7:2.2);chime(true)}}
function watchPerformance(now){frames++;if(now-fpsClock<2400)return;const fps=frames*1000/(now-fpsClock);frames=0;fpsClock=now;if(fps<42&&!degraded){degraded=true;quality*=.68;seed()} }
function frame(now){const dt=Math.min(34,now-last||16);last=now;time=now;if(moving){pointer.x=lerp(pointer.x,pointer.tx,.045);pointer.y=lerp(pointer.y,pointer.ty,.045)}flash*=.9;background();drawStars(now);drawGalaxy(now);drawFloaters(now);drawAmbientPetals();drawBursts();updateJourney(dt);if(flash>.015){ctx.fillStyle=`rgba(255,222,98,${flash*.065})`;ctx.fillRect(0,0,W,H)}watchPerformance(now);requestAnimationFrame(frame)}
function point(e){const r=canvas.getBoundingClientRect();return{x:e.clientX-r.left,y:e.clientY-r.top}}
addEventListener('pointermove',e=>{pointer.tx=(e.clientX/W-.5)*2;pointer.ty=(e.clientY/H-.5)*2;if(dragging&&++trailClock%(mobile?7:5)===0){const p=point(e);explode(p.x,p.y,.27)}});canvas.addEventListener('pointerdown',e=>{dragging=true;canvas.setPointerCapture?.(e.pointerId);const p=point(e);explode(p.x,p.y,.9)});canvas.addEventListener('pointerup',()=>dragging=false);canvas.addEventListener('pointercancel',()=>dragging=false);addEventListener('resize',resize,{passive:true});document.addEventListener('visibilitychange',()=>{if(document.hidden){last=0;dragging=false}});
$('#journey').addEventListener('click',startJourney);$('#closeMessage').addEventListener('click',()=>{document.body.classList.remove('modal');$('#message').classList.remove('show');$('#message').setAttribute('aria-hidden','true');$('#chapter').classList.remove('show');$('#progress').style.width='0'});$('#motion').addEventListener('click',e=>{moving=!moving;e.currentTarget.setAttribute('aria-pressed',moving)});$('#sound').addEventListener('click',e=>{if(!audio)startAudio();else{audio.on=!audio.on;audio.master.gain.setTargetAtTime(audio.on?.05:0,audio.ctx.currentTime,.5)}e.currentTarget.setAttribute('aria-pressed',audio?.on||false)});
function startAudio(){const AC=window.AudioContext||window.webkitAudioContext;if(!AC)return;const ac=new AC(),master=ac.createGain();master.gain.value=.04;master.connect(ac.destination);[98,146.83,196].forEach((f,i)=>{const o=ac.createOscillator(),g=ac.createGain();o.type=i%2?'sine':'triangle';o.frequency.value=f;g.gain.value=.05/(i+1);o.connect(g).connect(master);o.start()});audio={ctx:ac,master,on:true}}
function chime(big=false){if(!audio?.on)return;const now=audio.ctx.currentTime,notes=big?[523.25,659.25,783.99]:[659.25,783.99];notes.forEach((f,i)=>{const o=audio.ctx.createOscillator(),g=audio.ctx.createGain();o.frequency.value=f;g.gain.setValueAtTime(.001,now+i*.06);g.gain.exponentialRampToValueAtTime(.1,now+i*.06+.025);g.gain.exponentialRampToValueAtTime(.001,now+i*.06+.65);o.connect(g).connect(audio.master);o.start(now+i*.06);o.stop(now+i*.06+.7)})}
buildSprites();resize();explode(W*.7,H*.48,1.25);requestAnimationFrame(frame);
